CREATE TABLE [dbo].[CurrentDayPickups](
    [CurrentDayPickupID] [int] IDENTITY(1,1) NOT NULL,
    [CDPDefaultRouteID] [nvarchar](2) NULL,
    [CDPPreviousRouteID] [nvarchar](2) NULL,
    [CDPPickupDate] [datetime] NULL,
    [CDPCustomerID] [nvarchar](10) NULL,
    [CDPDriverName] [nvarchar](30) NULL,
    [CDPDriverMessage] [nvarchar](100) NULL,
    [CDPRouteName] [nvarchar](20) NULL,
    [CDPCustomerName] [nvarchar](30) NULL,
    [CDPComment] [nvarchar](30) NULL,
    [CDPDispatched] [bit] NOT NULL,
    [CDPDispatchTime] [datetime] NULL,
    [CDPNotes] [nvarchar](3) NULL,
    [CDPStation] [nvarchar](50) NULL,
    [CDPChecked] [bit] NOT NULL,
    [CDPDeleted] [bit] NOT NULL,
    [CDPSyncID] [nvarchar](50) NULL,
    [CDPCreatedBy] [nvarchar](50) NULL,
    [CDPCreatedTime] [datetime] NULL,
    [CDPEditedBy] [nvarchar](50) NULL,
    [CDPEditedTime] [datetime] NULL,
    [CDPSent] [bit] NOT NULL,
    [CDPSentTime] [datetime] NULL,
    [CDPSendConfirmed] [bit] NOT NULL,
    [CDPReceivedTime] [datetime] NULL,
    [PostedCount] [int] NULL,
    [Terminal] [nvarchar](50) NULL,

CREATE TABLE [dbo].[CurrentDayRoutes](
    [CurrentDayRouteID] [int] IDENTITY(1,1) NOT NULL,
    [CDRRouteID] [nvarchar](2) NULL,
    [CDRRouteName] [nvarchar](20) NULL,
    [CDRDefaultDriverID] [nvarchar](4) NULL,
    [CDRDriverLastName] [nvarchar](20) NULL,
    [CDRDriverMessage] [nvarchar](100) NULL,
    [CDRStation] [nvarchar](50) NULL,
    [CDRChecked] [bit] NULL,
    [CDRDate] [datetime] NULL,
    [CDRSyncID] [nvarchar](50) NULL,
    [CDRCreatedBy] [nvarchar](50) NULL,
    [CDRCreatedTime] [datetime] NULL,
    [CDREditedBy] [nvarchar](50) NULL,
    [CDREditedTime] [datetime] NULL,
    [CDRSent] [bit] NULL,
    [CDRSentTime] [datetime] NULL,
    [CDRSendConfirmed] [bit] NULL,
    [CDRReceivedTime] [datetime] NULL,
    [DUser] [nchar](30) NOT NULL,
    [Terminal] [nchar](30) NOT NULL,

CREATE TABLE [dbo].[customers](
    [CustomerTableID] [int] IDENTITY(1,1) NOT NULL,
    [CustomerID] [nvarchar](10) NULL,
    [CustomerName] [nvarchar](30) NULL,
    [Address1] [nvarchar](30) NULL,
    [Address2] [nvarchar](30) NULL,
    [City] [nvarchar](30) NULL,
    [State] [nvarchar](2) NULL,
    [Phone] [nvarchar](13) NULL,
    [Contact] [nvarchar](30) NULL,
    [ClosingTime] [nvarchar](5) NULL,
    [Comment] [nvarchar](30) NULL,
    [DefaultRouteID] [nvarchar](2) NULL,
    [CustomerSyncID] [nvarchar](50) NULL,
    [CustomerCreatedBy] [nvarchar](50) NULL,
    [CustomerCreatedTime] [datetime] NULL,
    [CustomerEditedBy] [nvarchar](50) NULL,
    [CustomerEditedTime] [datetime] NULL,
    [CustomerSent] [bit] NULL,
    [CustomerSentTime] [datetime] NULL,
    [CustomerSendConfirmed] [bit] NULL,
    [CustomerReceivedTime] [datetime] NULL,
    [DUser] [nchar](30) NOT NULL,
    [Terminal] [nchar](30) NOT NULL,
    [InfoString] [nchar](255) NULL,

CREATE TABLE [dbo].[DRIVER](
    [DriverTableID] [int] IDENTITY(1,1) NOT NULL,
    [DriverID] [nvarchar](4) NULL,
    [LastName] [nvarchar](20) NULL,
    [FirstName] [nvarchar](20) NULL,
    [MiddleInitial] [nvarchar](1) NULL,
    [DriverSyncID] [nvarchar](50) NULL,
    [DriverCreatedBy] [nvarchar](50) NULL,
    [DriverCreatedTime] [datetime] NULL,
    [DriverEditedBy] [nvarchar](50) NULL,
    [DriverEditedTime] [datetime] NULL,
    [DriverSent] [bit] NULL,
    [DriverSentTime] [datetime] NULL,
    [DriverSendConfirmed] [bit] NULL,
    [DriverReceivedTime] [datetime] NULL,

CREATE TABLE [dbo].[Pickup](
    [PickupTableID] [int] IDENTITY(1,1) NOT NULL,
    [DefaultRouteID] [nvarchar](2) NULL,
    [PickupDate] [datetime] NULL,
    [CustomerID] [nvarchar](5) NULL,
    [DriverName] [nvarchar](30) NULL,
    [RouteName] [nvarchar](20) NULL,
    [CustomerName] [nvarchar](30) NULL,
    [Comment] [nvarchar](30) NULL,
    [Monday] [bit] NULL,
    [Tuesday] [bit] NULL,
    [Wednesday] [bit] NULL,
    [Thursday] [bit] NULL,
    [Friday] [bit] NULL,
    [Dispatched] [bit] NULL,
    [DispatchTime] [datetime] NULL,
    [Notes] [nvarchar](3) NULL,
    [PickupSyncID] [nvarchar](50) NULL,
    [PickupCreatedBy] [nvarchar](50) NULL,
    [PickupCreatedTime] [datetime] NULL,
    [PickupEditedBy] [nvarchar](50) NULL,
    [PickupEditedTime] [datetime] NULL,
    [PickupSent] [bit] NULL,
    [PickupSentTime] [datetime] NULL,
    [PickupSendConfirmed] [bit] NULL,
    [PickupReceivedTime] [datetime] NULL,

CREATE TABLE [dbo].[PickupArchive](
    [PickupArchiveID] [int] IDENTITY(1,1) NOT NULL,
    [PADefaultRouteID] [nvarchar](2) NULL,
    [PAPickupDate] [datetime] NULL,
    [PACustomerID] [nvarchar](10) NULL,
    [PADriverName] [nvarchar](30) NULL,
    [PADriverMessage] [nvarchar](100) NULL,
    [PARouteName] [nvarchar](20) NULL,
    [PACustomerName] [nvarchar](30) NULL,
    [PAComment] [nvarchar](30) NULL,
    [PADispatched] [bit] NULL,
    [PADispatchTime] [datetime] NULL,
    [PADeleted] [bit] NULL,
    [PANotes] [nvarchar](3) NULL,

CREATE TABLE [dbo].[Posting](
    [PostingID] [int] IDENTITY(1,1) NOT NULL,
    [DataType] [varchar](50) NULL,
    [key] [int] NULL,
    [NumberofPendingUpdates] [int] NULL,
    [Originator] [varchar](50) NULL,
    [DefaultRouteId] [varchar](50) NULL,
    [PreviousRouteID] [varchar](50) NULL,
    [isDragnDrop] [bit] NOT NULL,

CREATE TABLE [dbo].[ROUTE2](
    [Route2TableID] [int] IDENTITY(1,1) NOT NULL,
    [RouteID] [nvarchar](2) NULL,
    [RouteName] [nvarchar](20) NULL,
    [DefaultDriverID] [nvarchar](4) NULL,
    [DriverMessage] [nvarchar](100) NULL,
    [Screen] [smallint] NULL,
    [RouteSyncID] [nvarchar](50) NULL,
    [RouteCreatedBy] [nvarchar](50) NULL,
    [RouteCreatedTime] [datetime] NULL,
    [RouteEditedBy] [nvarchar](50) NULL,
    [RouteEditedTime] [datetime] NULL,
    [RouteSent] [bit] NULL,
    [RouteSentTime] [datetime] NULL,
    [RouteSendConfirmed] [bit] NULL,
    [RouteReceivedTime] [datetime] NULL,
    [DUser] [nchar](30) NOT NULL,
    [Terminal] [nchar](30) NOT NULL,
