require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CurrendDayRoutesController do

  # This should return the minimal set of attributes required to create a valid
  # CurrendDayRoute. As you add validations to CurrendDayRoute, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all currend_day_routes as @currend_day_routes" do
      currend_day_route = CurrendDayRoute.create! valid_attributes
      get :index
      assigns(:currend_day_routes).should eq([currend_day_route])
    end
  end

  describe "GET show" do
    it "assigns the requested currend_day_route as @currend_day_route" do
      currend_day_route = CurrendDayRoute.create! valid_attributes
      get :show, :id => currend_day_route.id
      assigns(:currend_day_route).should eq(currend_day_route)
    end
  end

  describe "GET new" do
    it "assigns a new currend_day_route as @currend_day_route" do
      get :new
      assigns(:currend_day_route).should be_a_new(CurrendDayRoute)
    end
  end

  describe "GET edit" do
    it "assigns the requested currend_day_route as @currend_day_route" do
      currend_day_route = CurrendDayRoute.create! valid_attributes
      get :edit, :id => currend_day_route.id
      assigns(:currend_day_route).should eq(currend_day_route)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CurrendDayRoute" do
        expect {
          post :create, :currend_day_route => valid_attributes
        }.to change(CurrendDayRoute, :count).by(1)
      end

      it "assigns a newly created currend_day_route as @currend_day_route" do
        post :create, :currend_day_route => valid_attributes
        assigns(:currend_day_route).should be_a(CurrendDayRoute)
        assigns(:currend_day_route).should be_persisted
      end

      it "redirects to the created currend_day_route" do
        post :create, :currend_day_route => valid_attributes
        response.should redirect_to(CurrendDayRoute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved currend_day_route as @currend_day_route" do
        # Trigger the behavior that occurs when invalid params are submitted
        CurrendDayRoute.any_instance.stub(:save).and_return(false)
        post :create, :currend_day_route => {}
        assigns(:currend_day_route).should be_a_new(CurrendDayRoute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CurrendDayRoute.any_instance.stub(:save).and_return(false)
        post :create, :currend_day_route => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested currend_day_route" do
        currend_day_route = CurrendDayRoute.create! valid_attributes
        # Assuming there are no other currend_day_routes in the database, this
        # specifies that the CurrendDayRoute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CurrendDayRoute.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => currend_day_route.id, :currend_day_route => {'these' => 'params'}
      end

      it "assigns the requested currend_day_route as @currend_day_route" do
        currend_day_route = CurrendDayRoute.create! valid_attributes
        put :update, :id => currend_day_route.id, :currend_day_route => valid_attributes
        assigns(:currend_day_route).should eq(currend_day_route)
      end

      it "redirects to the currend_day_route" do
        currend_day_route = CurrendDayRoute.create! valid_attributes
        put :update, :id => currend_day_route.id, :currend_day_route => valid_attributes
        response.should redirect_to(currend_day_route)
      end
    end

    describe "with invalid params" do
      it "assigns the currend_day_route as @currend_day_route" do
        currend_day_route = CurrendDayRoute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CurrendDayRoute.any_instance.stub(:save).and_return(false)
        put :update, :id => currend_day_route.id, :currend_day_route => {}
        assigns(:currend_day_route).should eq(currend_day_route)
      end

      it "re-renders the 'edit' template" do
        currend_day_route = CurrendDayRoute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CurrendDayRoute.any_instance.stub(:save).and_return(false)
        put :update, :id => currend_day_route.id, :currend_day_route => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested currend_day_route" do
      currend_day_route = CurrendDayRoute.create! valid_attributes
      expect {
        delete :destroy, :id => currend_day_route.id
      }.to change(CurrendDayRoute, :count).by(-1)
    end

    it "redirects to the currend_day_routes list" do
      currend_day_route = CurrendDayRoute.create! valid_attributes
      delete :destroy, :id => currend_day_route.id
      response.should redirect_to(currend_day_routes_url)
    end
  end

end
